### ISSUE TITLE
ES2015 support

### ISSUE THREAD

**Issue by poke** [gwmaps/widget-map-floors#12]
I see that you are using ES2015 with all its glory for this widget. Do you intend to run a preprocessor on it later so this works on ES5 and on non-evergreen browsers? Because right now, this wouldn’t work in any Internet Explorer (for example).

On a completely unrelated note, you really don’t need to make a pull request for every change you have. Since you merge each one a minute later, they don’t really serve a purpose and just make the history [messier](https://github.com/GW2Wiki/widget-map-floors/network) ;) Of course, you can use them if you would like some input on changes (code review etc), but then you would need to give them a bit more time ;P

**Comment by codemasher** [comment]
> Here are the wiki statistics regarding browser access over the last 3 months: Chrome 65%, Firefox 19%, Safari 6%, Internet Explorer 3%

We've discussed this recently over here: https://gitter.im/arenanet/api-cdi?at=5771aa098c9263ba300cc8c2 (starts https://gitter.im/arenanet/api-cdi?at=57716b952214898a2196cdbb) - IE is a minority of 3% on the Wiki, i guess you're better off telling those few to upgrade :D 

> i'm going to add a "your browser is not fancy enough!" message in case.

(RE the PRs: i work on different machines and have to save my work state, too. i try to stick with "per feature")

**Comment by poke** [comment]
Failing for 3% of our user base, or 10% together with Safari, is _not_ really acceptable at all. 10% is _a lot of users_ that will end up breaking. I do not accept that, especially when transpiling to ES5 is such an easy thing to do.

I could agree with dropping support for earlier Internet Explorers (e.g. everything below 11), but dropping support completely for a public community site? Sorry to be a pain here, but not on my watch. I don’t believe that Stephane was aware of the implications you would take from getting those numbers ;)

Also remember that the syntax features in ES6 are an all-or-nothing thing. You cannot have good fallbacks for those. Unsupported syntax will break the whole script execution.

(And RE PRs, I don’t see how PRs help you with multiple machines. You can just push directly from multiple machines, and maybe use separate branches for individual features—which you can still merge without PRs ;P)

**Comment by codemasher** [comment]
Please do me a favour and don't generalize those numbers, especially IE and iOS - these are combined stats. You would need a breakdown of the actual OS and browser versions to see how many would actually be affected. It's 2016, and it's not too much for a desktop user to keep their brosers up-to-date, and to be honest - i don't go extra miles for this group (which is the main target group after all). I'd agree on mobile, but again, you'd need numbers. Next is: it affects only a very limited set of pages - now find the overlap.

Another reason: i made the first iteration almost exactly 3 years ago - it's available since then. So did Ish and Alex. Noone on the wiki cared about maps since. Every now and then everyone got excited how cool interactive maps are and nothing happened. So why bother? Give me a reason. My voice is unheard on the en-wiki - only few know me anyway. So, do your best - spark a public discussion for everyone on the wiki to participate. During this discussion will also turn out whether there are problems in browser/JS support. I won't rush to change everything back to an outdated language unless there is a real need. (ES2015 is official now, so i take that for granted)

**Comment by codemasher** [comment]
https://gitter.im/arenanet/api-cdi?at=579a635fac80b5ea3f146783
